#!/usr/bin/env php
<?php

$term = trim($argv[1]);

if ($term) {
    $params = array("term" => urlencode(trim($term)));
    $url = 'https://hleucka.ddns.net/api/v1/music/search?'.http_build_query($params);

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_HTTPHEADER, array( 'Content-Type: application/json'));
    $result = curl_exec($ch);
    curl_close($ch);

    if ($result) {
        $data = json_decode($result);
        foreach ($data->data as $one) {
            printf("%s — %s | %s\n", $one->artist, $one->title, $one->md5);
        }
    }
}
