#!/usr/bin/env bash
#
# soprano
# search for tracks via soprano music
# @author William Hleucka <william.hleucka@gmail.com>
#
# deps:
#  mpv
#  php (for now)
#

mpv_warning() {
    printf "Oops! Install mpv and try again\n"
	exit
}

which mpv >/dev/null || mpv_warning

read -p "Search: artist, album, or title: " query
if  [[ $query == '' ]]; then
    printf "Please provide a search term\n"
else
    SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
    selected=`$SCRIPT_DIR/search-request "$query" | tr -s ' ' | sort | fzf-tmux --header 'Select a track to play...' | cut -d " " -f1`
    echo $selected | tr " " "\n" | awk '{ print "https://hleucka.ddns.net/api/v1/music/play/"$0 }' > /tmp/soprano_list
    mpv --playlist=/tmp/soprano_list --no-video
fi
